Feature/headquarters
d2avids/rso pull request #14
Opened 2023-11-24 18:07 UTC by AlexanderChistyakov

2023-11-24 18:20 UTC, d2avids requested changes
Да, код стал чище!) Только нужно перенести функции в utils.py в рамках users и headquarters приложений

2023-11-24 18:20 UTC, d2avids commented on rso_backend/headquarters/models.py
> +def image_path(instance, filename):
Круто! Думаю, стоит перенести в utils.py в рамках приложения

2023-11-24 18:20 UTC, d2avids commented on rso_backend/headquarters/models.py
> +    """
Круто, подробная дока 😎

2023-11-24 18:20 UTC, d2avids commented on rso_backend/headquarters/models.py
> +    )
Четко зарефакторил!

2023-11-24 18:20 UTC, d2avids commented on rso_backend/headquarters/models.py
> +def delete_image_with_object_central_headquarter(sender, instance, **kwargs):
тоже в utils.py

2023-11-24 18:20 UTC, d2avids commented on rso_backend/headquarters/models.py
> +def delete_image_with_object_regional_headquarter(sender, instance, **kwargs):
тоже в утиль)

2023-11-24 18:20 UTC, d2avids commented on rso_backend/headquarters/models.py
> +def delete_image_with_object_detachment(sender, instance, **kwargs):
то же самое

2023-11-24 18:20 UTC, d2avids commented on rso_backend/users/models.py
> +def image_path(instance, filename):
в утиль

2023-11-24 18:20 UTC, d2avids commented on rso_backend/users/models.py
> +def document_path(instance, filename):
в утиль

2023-11-24 21:01 UTC, AlexanderChistyakov commented on rso_backend/headquarters/models.py
> +    """
Codeium помог)

2023-11-24 21:03 UTC, AlexanderChistyakov commented on rso_backend/headquarters/models.py
> +def delete_image_with_object_central_headquarter(sender, instance, **kwargs):
Декоратор мешает. Придется в утилс писать столько же раз эту функцию, сколько и здесь. В таком случае для наглядности предлагаю оставить здесь.

2023-11-25 10:43 UTC, AlexanderChistyakov commented on rso_backend/headquarters/models.py
> +def delete_image_with_object_central_headquarter(sender, instance, **kwargs):
Сделано

2023-11-25 10:43 UTC, AlexanderChistyakov commented on rso_backend/headquarters/models.py
> +def image_path(instance, filename):
Сделано

2023-11-25 10:43 UTC, AlexanderChistyakov commented on rso_backend/headquarters/models.py
> +def delete_image_with_object_regional_headquarter(sender, instance, **kwargs):
Сделано

2023-11-25 10:43 UTC, AlexanderChistyakov commented on rso_backend/headquarters/models.py
> +def delete_image_with_object_detachment(sender, instance, **kwargs):
Сделано

2023-11-25 10:43 UTC, AlexanderChistyakov commented on rso_backend/users/models.py
> +def image_path(instance, filename):
Сделано

2023-11-25 10:43 UTC, AlexanderChistyakov commented on rso_backend/users/models.py
> +def document_path(instance, filename):
Сделано

2023-11-25 10:50 UTC, d2avids approved these changes
все замечательно!

2023-11-25 10:50 UTC, merged