add new permission
d2avids/rso pull request #178
Opened 2024-02-29 19:29 UTC by AlexanderChistyakov

Добавлен пермишен и заготовки для тестирования фичи

2024-03-02 12:39 UTC, d2avids requested changes

2024-03-02 12:39 UTC, d2avids commented on rso_backend/api/permissions.py
> +        if request_user.id == obj_user_id:
верно, это первая проверка

2024-03-02 12:39 UTC, d2avids commented on rso_backend/api/permissions.py
> +        prepared_data = (
Второй проверкой должно быть есть ли пользователь в таблице UserVerificationRequest. Зачем давать возможность смотреть данные пользователя, который не подавал заявку на верификацию, или же его уже верифицировали

2024-03-02 12:39 UTC, d2avids commented on rso_backend/api/permissions.py
> +            self.prepare_data_commander(request)
В этой функции идут лишние вычисления по штабам, которые нам не нужны. Намного выгоднее и правильнее с точки зрения логики проверить, является ли запрашивающий пользователь командиром в РШ - RegionalHeadquarter.objects.get(commander=request_user) с отловом исключения и затем провести такую же проверку для отряда. Это будет в 3 раза выгоднее по затратам ресурсов.

К тому же, на будущее (когда будешь рефакторить пермишены) - у тебя должно быть 6 таких функций для поиска командира на каждом уровне + 6 таких же функций для поиска доверенных (там то же самое, только вместо модели штаба используется модель участников). И, для тех случаев, где тебе нужно использовать все 6 функций (то есть проверять командирство на каждом уровне), ты можешь написать 7-ю функцию, которая будет составлять словарь из всех предыдущих 6. Предлагаю здесь начать этот маленький шаг к улучшению кода и написать первые две функции для этого случая и использовать их здесь вместо prepare_data (который к тому же выполняет лишнюю логику с сериализацией)

2024-03-02 12:39 UTC, d2avids commented on rso_backend/api/permissions.py
> +            obj_detachment = UserDetachmentPosition.objects.filter(
Зачем это нужно? Если он командир, то он не будет находиться в этой модели. Кроме того, get и ловить экспешн выгоднее, чем фильтр. Юзер может состоять на одном уровне только в одной стр. единице, так что здесь предпочтительнее get

2024-03-02 12:39 UTC, d2avids commented on rso_backend/api/permissions.py
> +                ) == obj_detachment
непонятно что дает это сравнение (является ли юзер командиром там, где он состоит? опять же, возвращаемся выше - если юзер командир в отряде - он не находится в модели участников в соответствии с нашим кодом)

2024-03-02 13:37 UTC, viva-lavita commented on rso_backend/tests/test_users/test_users.py
> +        )
if response.status_code == HTTPStatus.OK:
    ... тестим, что вывод соответсвует ожидаемому)

2024-03-02 13:37 UTC, viva-lavita commented on rso_backend/tests/test_users/test_users.py
> +            f'/api/v1/rsousers/{user_with_position_in_detachment.pk}/'
Я бы вынесла все части эндпоинта в переменные класса. Т.к. если эндпоинт поменяется, менять его нужно будет только в одном месте, а так - в каждом тесте..

2024-03-03 10:18 UTC, d2avids approved these changes

2024-03-03 10:18 UTC, d2avids commented on rso_backend/api/utils.py
> +def get_detachment_commander_num(user):
красава!

2024-03-03 10:18 UTC, d2avids commented on rso_backend/api/permissions.py
> +        except (
гуд

2024-03-03 11:19 UTC, merged