Feature/users roles
d2avids/rso pull request #58
Opened 2023-12-10 12:34 UTC by AlexanderChistyakov

Постарался проверить разные варианты работы различных вьюсетов. Насколько я увидел, всё работает. Дальше в разработке нужно будет каждый следующий вьюсет перепроверять с пермишенами.

2023-12-10 21:35 UTC, d2avids requested changes
Мне очень понравился пулл реквест. Работа грандиозная, поэтому багов и правок не избежать!
Пофиксил ошибку с тем, что не создавался отряд из-за обязательного поля city. Его не было в сериализаторе. Сделал коммит.

Также сделал некоторые тесты: 
1. Региональный командир не смог отредактировать инфу о своем штабе. Доверенное лицо тоже. Зато он смог создать штабы и отредактирвать, как и доверенные лица.
2. Доверенное лицо и командир смогли создать отряд не привязанный к своему региональному штабу. А именно, доверенное лицо Воронежского штаба создало отряд, привязанный к Московскому штабу. Полагаю, что такая же проблема будет и с местным, и с образовательным, и на всех уровнях (т.е. командир/доверенное НЕ ДОЛЖНЫ иметь возможность создать единицы, не привязанные к себе. в том числе, командир окружного НЕ МОЖЕТ создать образовательный штаб, который через привязку к региональному будет привязан к другому окружному. Эти проверки надо реализовывать на всех уровнях)
3. Как указали в чате, доверенные лица могут редактировать информацию своего штаба за исключением блока основная информация.

По-любому нужно будет тестить еще.

2023-12-10 21:35 UTC, d2avids commented on rso_backend/api/permissions.py
> +    возвращают True,если редактируют штабы ниже своего.
`если редактируют **свой штаб** или штабы ниже своего`, верно? А еще в доке после запятой пробел пропущен :)))

2023-12-10 21:35 UTC, d2avids commented on rso_backend/api/permissions.py
> +        )
очень круто!

2023-12-10 21:35 UTC, d2avids commented on rso_backend/api/permissions.py
> +    Роли 'админ' и 'командир центрального штаба' возвращают True.
Кстати, у центрального штаба тоже могут быть доверенные лица. И они имеют такие же права, как и командир. Надо это учесть в коде и в доке.

2023-12-10 21:35 UTC, d2avids commented on rso_backend/api/permissions.py
> +            or is_stuff_or_central_commander(request)
И сюда вот `or check_trusted_user`)

2023-12-10 21:35 UTC, d2avids commented on rso_backend/api/permissions.py
> +class IsDistrictCommander(BasePermission):
Предлагаю сделать ренейминг моделей, начиная с этой и ниже по примеру: `IsDistrictCommanderOrTrusted`

2023-12-10 21:35 UTC, d2avids commented on rso_backend/api/permissions.py
> +        roles_with_rights = [
очень креативное решение со списком ролей и моделей для всех моделей по иерархии ниже, мне нравится) наверняка можно было придумать как-то иначе, но выглядит красиво, приятно и читабельно, так что - зачет!

P.S. роли и модели можно было бы вынести в constants.py и там доработать нейминг. regional_roles_with_rights, `regional_models` и так далее. Хотя так тоже классно) на твой вкус.

2023-12-10 21:35 UTC, d2avids commented on rso_backend/api/permissions.py
Потрясает! Отличная работа, чистый и приятный код!

2023-12-10 21:35 UTC, d2avids commented on rso_backend/api/utils.py
Им здесь и место)

2023-12-10 21:35 UTC, d2avids commented on rso_backend/headquarters/models.py
> +        default=PositionsOption.candidate,
отлично

2023-12-10 21:35 UTC, d2avids commented on rso_backend/headquarters/models.py
> +        unique=True,
то, что нужно

2023-12-10 21:35 UTC, d2avids commented on rso_backend/headquarters/signal_handlers.py
баги пофикшены!)

2023-12-10 21:35 UTC, d2avids commented on rso_backend/users/constants.py
рефакторингу быть!)

2023-12-11 09:18 UTC, AlexanderChistyakov commented on rso_backend/api/permissions.py
> +class IsStuffOrCentralCommander(BasePermission):
Может в будущем так и придется сделать, пока что не понятно будут ли эти роли смешиваться.

2023-12-11 09:25 UTC, AlexanderChistyakov commented on rso_backend/api/permissions.py
> +class IsDistrictCommander(BasePermission):
Не стал так называть, потому что тогда нужно писать еще длиннее:
IsDistrictCommanderOrTrustedOrStuffOrReadOnly.  Думаю это избыточно. В доке все прописал

2023-12-11 09:28 UTC, AlexanderChistyakov commented on rso_backend/api/permissions.py
> +        roles_with_rights = [
Много будет констант с длинным названием и на все названия нужно придумать индивидуальные. Здесь довольно наглядно получилось, предлагаю оставить.

2023-12-11 09:31 UTC, AlexanderChistyakov commented on rso_backend/api/utils.py
> +    user_id = request.user.id
Галя, у нас отмена

2023-12-11 11:59 UTC, AlexanderChistyakov commented on rso_backend/api/utils.py
> +    position_name = ''
Согласен. Убрал

2023-12-27 19:21 UTC, merged